### PR TITLE
Set seeds by chapter number

### LINKED ISSUE #128: Chapter-oriented seeds
Since we've been moving away from unusual numbers for seeds, it might be a good idea to number them by chapter. 

For example, the first seed in chapter 5 would be 501, chapter 11 starts with 1101, and so on.

### PR DESCRIPTION
**Pull request by juliasilge**
Closes #128 

I think this is about the best, most consistent job we can do. There are sort of gray areas in here but I think this is probably a good way to go.

### CODE REVIEW

**Comment by juliasilge** [comment]
Well, that is an _interesting_ failure 😬

I can reproduce this locally:

``` r
library(workflowsets)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

two_class_res
#> # A workflow set/tibble: 6 × 4
#>   wflow_id      info             option    result   
#>   <chr>         <list>           <list>    <list>   
#> 1 none_cart     <tibble [1 × 4]> <opts[3]> <tune[+]>
#> 2 none_glm      <tibble [1 × 4]> <opts[3]> <rsmp[+]>
#> 3 none_mars     <tibble [1 × 4]> <opts[3]> <tune[+]>
#> 4 yj_trans_cart <tibble [1 × 4]> <opts[3]> <tune[+]>
#> 5 yj_trans_glm  <tibble [1 × 4]> <opts[3]> <rsmp[+]>
#> 6 yj_trans_mars <tibble [1 × 4]> <opts[3]> <tune[+]>

bind_rows(two_class_res, two_class_res)
#> # A tibble: 12 × 4
#>    wflow_id      info             option    result   
#>    <chr>         <list>           <list>    <list>   
#>  1 none_cart     <tibble [1 × 4]> <opts[3]> <tune[+]>
#>  2 none_glm      <tibble [1 × 4]> <opts[3]> <rsmp[+]>
#>  3 none_mars     <tibble [1 × 4]> <opts[3]> <tune[+]>
#>  4 yj_trans_cart <tibble [1 × 4]> <opts[3]> <tune[+]>
#>  5 yj_trans_glm  <tibble [1 × 4]> <opts[3]> <rsmp[+]>
#>  6 yj_trans_mars <tibble [1 × 4]> <opts[3]> <tune[+]>
#>  7 none_cart     <tibble [1 × 4]> <opts[3]> <tune[+]>
#>  8 none_glm      <tibble [1 × 4]> <opts[3]> <rsmp[+]>
#>  9 none_mars     <tibble [1 × 4]> <opts[3]> <tune[+]>
#> 10 yj_trans_cart <tibble [1 × 4]> <opts[3]> <tune[+]>
#> 11 yj_trans_glm  <tibble [1 × 4]> <opts[3]> <rsmp[+]>
#> 12 yj_trans_mars <tibble [1 × 4]> <opts[3]> <tune[+]>
```

<sup>Created on 2022-02-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

@DavisVaughan do you know of anything that has changed lately in vctrs or rlang that would [upset the `compat_vctrs.R` setup](https://github.com/tidymodels/workflowsets/blob/main/R/compat-vctrs.R) so we can bind rows? I am most suspicious of how we are using dev pillar here.

**Comment by juliasilge** [comment]
The problem above ⬆️  was from the workflowsets involving different sets of resamples, because of the seed changes.

**Comment by topepo** [comment]
I ran locally and, overall, it looks pretty good. Some chapters already had the new seed scheme so those are 💯 

There are a few things that we might change: 

* We'll need to update the BO and SA verification function (no big deal). 

* The random and space filling grids are hard to differentiate. Maybe we should do 25 instead of 15 points. 

* The racing results are slightly different (2 left at the end instead of 1). I think that the website is fine but the text in the print edition probably has to change. We should check the alt-text too. 

* The SA converged really quickly with this seed and some of the code silently failed since there were 25 iterations instead of the expected 50. We might turn off the early stopping to let it go to 50 (or change it to 25). The results are good but will need some adjustments. 

* The dimension reduction chapter is using chapter 17 seeds (e.g. 1701) instead of 16 (since we re-ordered)

Do you want me to tackle some of these?

**Comment by topepo** [comment]
For SA here are the results if we let it early stop versus go all 50 iterations: 

2-phases

5-phases

I'm inclined to use 50 since it gives a better sense of how the search works. Either way, I'll make a note that "the random numbers were good here and others would have taken longer to converge."

**Comment by juliasilge** [comment]
I went through this again and addressed most of these. I checked in `.RData` files that reflect the new seeds, I bumped up the number of points to show, etc.

Ch 14 still needs some checking/work, and I think I've got myself really confused on it. Can you take a look, for bot the Bayesian optimization and simulated annealing? I think they are both messed up right now, especially related to some of that generated text.

I'll go through Ch 18 and add some seeds.

**Pull request merged**
