### PR TITLE
Update 20-ensemble-models.Rmd

### PR DESCRIPTION
**Pull request by xiaochi-liu**
Not sure whether I understand correctly here. We are using five repeats of 10-fold cross-validation, so shouldn't we have $5 \times 10 = 50$ assessment sets?

### CODE REVIEW

**Comment by juliasilge** [comment]
I'm pretty sure this one is right as published. 

One repeat of 10-fold (or 3-fold, etc) CV generates _one_ assessment set prediction for each training set sample:



Notice that each sample from the training set gets a prediction _one_ time, when it is in the assessment set ("estimate performance using...").

If we repeated that 5 times, we would get five assessment set predictions for each observation in the training set.

**Comment by xiaochi-liu** [comment]
Thank you very much for your kind guidance, Julia!

Is there a different understanding of "the assessment set"? Based on this figure:

image

My understanding is like this:

image

When we do 3-fold cross-validation, we get 3 assessment sets. These 3 assessment sets bind together so that each sample from the training set gets a prediction. Thus, if we do 5 repeats 3-fold cross-validation, we will have $5 \times 3 = 15$ assessments.

**Comment by juliasilge** [comment]
This is exactly right:

> When we do 3-fold cross-validation, we get 3 assessment sets. These 3 assessment sets bind together so that each sample from the training set gets a prediction. Thus, if we do 5 repeats 3-fold cross-validation, we will have 5×3=15 assessments.

With 3-fold CV, there are 3 assessment sets and each training set observation is in _one_ of these, so each training set observation gets _one_ prediction, when it is in the assessment set. There are no predictions when something is in the analysis set.

If we repeat that 5 times, there will be 15 assessments sets. Each training set observation will be in 5 assessment sets (one at each repeat) so there will be 5 predictions made for each training set observation.

**Comment by xiaochi-liu** [comment]
Got it.  Now I totally understand. Thank you very much, Julia!

**Pull request closed without merging**
